max_obstacle_height: 0.60 # assume something like an arm is mounted on top of the robot
obstacle_range: 1.5 # 障害物を認識する範囲
raytrace_range: 2.0 # ロボットが前方をクリア(認識?)する範囲
# robot_radius: 0.30 # ロボットの半径
footprint: [[-0.07, -0.22], [-0.07, 0.22], [0.43, 0.22], [0.43, -0.22]] # ロボットの形状、中心は(0,0)
inflation_radius: 0.50 # 障害物を認識したときにロボットが避ける距離

# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

observation_sources: scan # どのセンサーを使うか

scan: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}