joy: {
  # Rボタンを押しながらじゃないと動かない
  safe_button: 5,

  assign_x: 1,
  assign_y: 3,
  assign_z: 0,
  assign_x_straight: 7,
  assign_z_rotate: 6,

  max_x: 0.05,
  max_y: 0.05,
  max_z: 0.05,
}

twoWD: {
  first_x: 0,
  first_y: 0,

  radius: 0.1,
  tread: 0.3,
  enc_cpr: 4096,
}

arduino: {
  # PIDの順
  gainL: [10.0, 1.0, 1.0],
  gainR: [10.0, 1.0, 1.0],
}