joy: {
  assign_x: 0,
  assign_y: 1,
  assign_z: 3,

  max_x: -0.05,
  max_y: 0.05,
  max_z: 0.025,
}

twoWD: {
  first_x: 0,
  first_y: 0,

  radius: 0.1,
  tires_dist: 0.3,
  encoder_cpr: 8192,
}

Arduino: {
  # PIDの順
  gainL: [7.0, 1.0, 0.3],
  gainR: [7.0, 1.0, 0.3],
}